apiVersion: run.tanzu.vmware.com/v1alpha1       #TKG API group endpoint
kind: TanzuKubernetesCluster                    #required parameter
metadata:
  name: tkc-workload-c1                        #cluster name, user defined
  namespace: default                            #supervisor namespace
spec:
  distribution:
    version: v1.20                              #resolved kubernetes version
  topology:
    controlPlane:
      count: 1                                  #number of control plane nodes
      class: best-effort-medium                  #vmclass for control plane nodes
      storageClass: tanzu-storage   #storageclass for control plane
    workers:
      count: 3                                  #number of worker nodes
      class: best-effort-medium                  #vmclass for worker nodes
      storageClass: tanzu-storage   #storageclass for worker nodes
#  settings:
#    network:
#      pods:
#        cidrBlocks: ["192.168.0.0/22"]         #Cannot overlap with Supervisor Cluster
#      services:
#        cidrBlocks: ["10.96.0.0/22"]
