apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kuard
  name: kuard
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:blue
    name: kuard
  dnsPolicy: ClusterFirst
  restartPolicy: Never
